# Generated by Django 3.2 on 2021-05-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('gpus', '0002_gpu_gpu_subscription'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='gpus',
            field=models.ManyToManyField(through='subscriptions.Subscription', to='gpus.GPU'),
        ),
    ]
