# Generated by Django 3.2 on 2021-05-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gpus', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpus.gpu')),
                ('sub_subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriber')),
            ],
        ),
    ]
