# Generated by Django 3.2 on 2021-05-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, unique=True)),
                ('manufacturer', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
            ],
        ),
    ]
