# Generated by Django 3.2 on 2021-05-18 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('gpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='gpu_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscription'),
        ),
    ]
