# Generated by Django 3.2 on 2021-05-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpus', '0002_gpu_gpu_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='alias',
            field=models.CharField(default='blank', max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
