# Generated by Django 3.2 on 2021-05-07 06:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gpu', models.ForeignKey(default='brand', on_delete=django.db.models.deletion.CASCADE, to='suboverview.gpu')),
            ],
        ),
    ]
