# Generated by Django 3.2 on 2021-05-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='gpu',
            field=models.ForeignKey(default='brand', on_delete=django.db.models.deletion.CASCADE, to='SubscriptionManagement.gpu'),
        ),
    ]
