# Generated by Django 3.2 on 2021-05-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={},
        ),
        migrations.AlterModelManagers(
            name='subscriber',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='password',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='username',
        ),
    ]
